# This is the range that the sound effect is played.
# If this is set to -1, it will play to all players on the server.
# If this is set to 0, it will only play to the player.
# Any other number represents the range in blocks that the sound can be heard for.
range: -1

# This is the volume that the sound effect is played at.
# Unless I am mistaken, minimum value is 0 and maximum value is 10.0
volume: 1.0

# This is the pitch that the sound effect is played at.
# Unless I am mistaken, minimum value is 0 and maximum value is 1.0
pitch: 1.0

# This is a collection of lists of aliases for every sound that can be played in Minecraft.
# Since there are so many sounds, not all of them have been added here, however this plugin
# has been developed so that you can add sounds yourself, for example, if more sounds are
# added to Minecraft. More information on how to do this can be found on the BukkitDev page.
# https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/browse/src/main/java/org/bukkit/Sound.java
aliases:
  entity_generic_explode:
  - explode
  - boom
  - tnt
  entity_cat_ambient:
  - meow
  entity_cat_purr:
  - purr
  entity_cat_purreow:
  - purreow
  entity_cow_ambient:
  - cow
  - moo
